import React from 'react'
import ReactDOM from 'react-dom'
import Hooks from './Hooks'
import Old from './Old'
import Context from './Context'
import Reducer from './Reducer'
import PrimaryRedux from './primaryRedux/PrimaryRedux'
import Optimize from './optimize/Optimize'
import Ref from './Ref'
ReactDOM.render(<Ref />, document.getElementById('root'))